import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapJsLoader from "@/utils/BootstrapJsLoader";
import React from "react";
import NavBar, {NavItem} from "@/components/NavBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const itemNavs: NavItem[] = [
    {label: "Home", href: ""},
    {label: "Store", href: ""},
    {label: "Collection", href: ""},
    {label: "About", href: ""}
];

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <BootstrapJsLoader/>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
                <NavBar items={itemNavs}/>
            </header>
            <main>
                {children}
            </main>
        </body>
        </html>
    );
}
